{
  "openapi": "3.0.0",
  "info": {
    "version": "2.0.0-beta",
    "title": "API Documentation v2 | Printful",
    "description": "# About the Printful API\n\n<div class=\"alert alert-info\">\n    <h3>Welcome to API v2 BETA</h3> \n    <ul>\n        <li>\n           We’re excited to inform you that the new major version of our API just went live, and we want to invite you to participate in the Open Beta test. \n            Please keep in mind that this release is still in BETA, although all presented endpoints can be used in a production environment. \n            Since this is a BETA release, we are keen[...]",
    "contact": {
      "name": "Printful developer support",
      "url": "https://www.printful.com/docs/support",
      "email": "devsupport@printful.com"
    },
    "x-logo": {
      "url": "https://static.cdn.printful.com/dist-pf/image-assets/off-center-full-color-black.1de1e822b15b8e74075c8d1fa631d4e3.svg",
      "backgroundColor": "#FFFFFF",
      "altText": "Printful"
    }
  },
  "servers": [
    {
      "url": "https://api.printful.com",
      "description": "The Printful API is a RESTful API, that uses the HTTP protocol for communication. HTTP GET, POST, PUT and DELETE methods are used to access the API."
    }
  ],
  "tags": [
    {
      "name": "Rate Limiting",
      "description": "Printful implements rate limiting to ensure the stability of the API while\nkeeping it fair for all users. Rate limiting is handled differently depending\non the version and endpoint being used.\n\n### Header values\n\nPrintful uses the following header values to communicate rate limits:\n\n```\nX-Ratelimit-Limit\nX-Ratelimit-Remaining\nX-Ratelimit-Reset\nX-Ratelimit-Policy\n```\n\nHowever, the meaning of these values changes depending on the algorithm used.\n\n### V1 Rate [...]"
    },
    {
      "name": "Catalog v2",
      "description": "## What is a catalog product?\nA catalog product refers to a blank product and its variants. Each variant can be used as the base for custom designs. Catalog product consists of multiple catalog variants each of which might be a combination of size and color or it might be a variation with e.g. tear away label. The entire hierarchy is shown in the diagram below:\n\n[<img src=\"images/catalog/catalog_product_diagram.png#center\" width=\"300\"/>](images/catalog/catalog_produc[...]"
    },
    {
      "name": "Sync v2",
      "description": "Sync v2"
    },
    {
      "name": "Orders v2",
      "description": "## Order Building\n\nYou can create a draft order without order items but you won’t be able to confirm it until at least one order item are added to that order.\nWith this approach, you can create a draft order with all necessary recipient data and add items to it as you go (similar to a shopping cart)\nby using [Create Order Item](#operation/createItemByOrderId). After every order item addition, the order cost will be re-calculated.\n\nA minimal DRAFT order can be created [...]"
    },
    {
      "name": "Mockup Generator v2",
      "description": "This resource is used to visualize how the designed products will look like. Since this is a resource-heavy operation we process the requests asynchronously. That means that you won't get the results\nimmediately, and instead you will get task ID which you could use to retrieve the mockups once they are done\nusing _[Retrieve mockup generator tasks](#operation/getMockupGeneratorTasks)_.\nYou can also subscribe to a webhook _[Mockup generator task finished event](#operation/[...]"
    },
    {
      "name": "Webhook v2",
      "description": "Webhooks are an API feature that allows your system to receive notifications about certain events.\n\nWhen an event occurs, for example one of the products you use comes back in stock, the Printful server\nwill make a POST request to your defined\nURL that will contain a JSON object in the request body.\nYour server has to respond with HTTP status `200 OK`,\notherwise, the request will be retried in increasing intervals\n(after 1, 4, 16, 64, 256 and 1024 minutes).\n\nThe JS[...]"
    },
    {
      "name": "Examples",
      "description": "# Catalog API examples\n\n## Using size guides\n\nIn this example, we'll fetch the size guides for the\n\"Women's Basic Organic T-Shirt | SOL'S 02077\" product (ID: 561).\n\nWe use the default `en_US` locale and don't provide the `unit` parameter, so the measurement values will be returned in\ninches.\n\nURL: https://api.printful.com/v2/catalog-products/561/sizes\n\n<details>\n    <summary>Whole response body</summary>\n\n```javascript\n{\n  \"data\": {\n    \"product_id\":[...]"
    }
  ],
  "paths": {
    "/v2/catalog-products": {
      "get": {
        "summary": "Retrieve a list of catalog products",
        "description": "This endpoint retrieves a list of the products available in Printful's catalog. The list is paginated and can be filtered using various filters. The information returned includes details on how each product can be designed, such as the available placements, techniques, and additional options.\nFor a visual representation of the design data, please see the following diagram:\n[<img src=\"images/catalog/design_data_diagram.png#center\" width=\"700\"/>](images/catalog/design[...]",
        "operationId": "getProducts",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-products/{id}": {
      "get": {
        "summary": "Retrieve a single catalog product",
        "description": "Returns information about a single specified catalog product. [See catalog product](#tag/Catalog-v2/What-is-a-catalog-product)\n",
        "operationId": "getProductById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-variants/{id}": {
      "get": {
        "summary": "Retrieve information about specific catalog variant",
        "description": "Returns information about single specified catalog variant. [See catalog variant](#tag/Catalog-v2/What-is-a-catalog-variant)\n",
        "operationId": "getVariantById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-products/{id}/catalog-variants": {
      "get": {
        "summary": "Retrieve information about catalog product variants",
        "description": "Returns information about all catalog variants associated with the specified\ncatalog product. [See catalog variant](#tag/Catalog-v2/What-is-a-catalog-variant)\n",
        "operationId": "getProductVariantsById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-categories": {
      "get": {
        "tags": ["Catalog v2"],
        "summary": "Retrieve a list of catalog categories",
        "description": "Returns list of all categories that are present in the catalog. The categories specify the type of the product that is associated with it. For example, the category \"Men’s T-shirts\" indicates that the product is a subgroup of T-shirts specifically targeted at Men.\nCategories can be used to filter the product list by specific tags [See categories_ids](#operation/getProducts)\n",
        "operationId": "getCategories",
        "security": [
          {
            "OAuth": []
          }
        ]
      }
    },
    "/v2/catalog-categories/{id}": {
      "get": {
        "summary": "Retrieve information about specific category",
        "description": "Returns information about a specific catalog category. The categories specify the type of the product that is associated with it. For example, the category \"Men’s T-shirts\" indicates that the product is a subgroup of T-shirts specifically targeted at Men.\nCategories can be used to filter the product list by specific tags [See categories_ids](#operation/getProducts)\n",
        "operationId": "getCategoryById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-products/{id}/catalog-categories": {
      "get": {
        "summary": "Retrieve a list of catalog product categories",
        "description": "To retrieve information about a particular category, use this feature. It returns details about a specific catalog category. Categories help identify the type of product associated with them. For instance, the category \"Men's T-shirts\" denotes that the product is a subgroup of T-shirts intended for men.\n",
        "operationId": "getCategoriesByProductId",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-products/{id}/sizes": {
      "get": {
        "summary": "Retrieve size guide for a catalog product",
        "description": "Returns information about the size guide for a specific product.",
        "operationId": "getProductSizeGuideById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-products/{id}/prices": {
      "get": {
        "summary": "Retrieve catalog product prices",
        "description": "Calculates prices for specific catalog product based on selling region and specified currency. Calculations also include Store discounts. Selling region is used to specify product production currency, that is the price that the product is natively manufactured in. Different selling regions might affect the overall price amount. Currency parameter is used only to define the currency that the prices will be displayed in.\n",
        "operationId": "getProductPricesById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-variants/{id}/prices": {
      "get": {
        "summary": "Retrieve pricing information for the catalog variant",
        "description": "Return pricing information from a single variant and the parent product",
        "operationId": "getVariantPricesById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-products/{id}/images": {
      "get": {
        "summary": "Retrieve blank images for a catalog product",
        "description": "This feature helps to fetch blank images for a catalog product. These blank images are always white and semi-transparent and can be colored by the user on the client-side as per the specified color in the `data.color` field. The endpoint allows filtering of the result based on the type of the mockup, the placement, and the color of the product.\n",
        "operationId": "getProductImagesById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-variants/{id}/images": {
      "get": {
        "summary": "Retrieve blank images for a catalog variant",
        "description": "Returns images for a specified Variant.",
        "operationId": "getVariantImagesById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-products/{id}/mockup-styles": {
      "get": {
        "summary": "Retrieve catalog product mockup styles",
        "description": "Returns information about available mockup styles for specified catalog product.\n",
        "operationId": "retrieveMockupStylesByProductId",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-products/{id}/mockup-templates": {
      "get": {
        "summary": "Retrieve catalog product mockup templates",
        "description": "Returns positional data for specified catalog product mockups. The data from this endpoint could be used\nto generate your own mockups without the need to use Printful's mockup generator.\n![Mockup template](images/mockups/mockup_template.png)\n",
        "operationId": "getMockupTemplatesByProductId",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-products/{id}/availability": {
      "get": {
        "summary": "Retrieve catalog product stock availability",
        "description": "Provides information about the catalog product stock status. Stock availability is grouped by variants &rarr; techniques &rarr; selling regions.\n",
        "operationId": "getProductStockAvailabilityById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/catalog-variants/{id}/availability": {
      "get": {
        "summary": "Retrieve catalog variant stock availability",
        "description": "Provides information about the catalog variant stock status. Stock availability is grouped by variants &rarr; techniques &rarr; selling regions.\n",
        "operationId": "getVariantStockAvailabilityById",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Catalog v2"]
      }
    },
    "/v2/orders": {
      "get": {
        "summary": "Get Orders",
        "description": "Returns paginated Order list",
        "operationId": "getOrders",
        "security": [
          {
            "OAuth": ["orders/read"]
          }
        ],
        "tags": ["Orders v2"]
      },
      "post": {
        "summary": "Create Order",
        "description": "Creates a new order",
        "operationId": "createOrder",
        "security": [
          {
            "OAuth": ["orders"]
          }
        ],
        "tags": ["Orders v2"]
      }
    },
    "/v2/orders/{order_id}": {
      "get": {
        "summary": "Get Order",
        "description": "Returns Order",
        "operationId": "getOrder",
        "security": [
          {
            "OAuth": ["orders/read"]
          }
        ],
        "tags": ["Orders v2"]
      },
      "delete": {
        "summary": "Delete Order",
        "description": "<div class=\"alert alert-danger\">\n  <strong>Warning:</strong> The DELETE HTTP method in version 2 of order in the \n  API will delete the order if the order can be deleted. This is distinct from \n  version 1 where the DELETE method will actually cancel the order rather than \n  delete it. Please, keep this in mind if you are migrating to version 2 from \n  version 1\n</div>\n\nDelete the order if it can be deleted. An order can be deleted if it's status is\n`draft`, `f[...]",
        "operationId": "deleteOrder",
        "security": [
          {
            "OAuth": ["orders"]
          }
        ],
        "tags": ["Orders v2"]
      },
      "patch": {
        "summary": "Update Order",
        "description": "Make a partial update of an order.",
        "operationId": "updateOrder",
        "security": [
          {
            "OAuth": ["orders"]
          }
        ],
        "tags": ["Orders v2"]
      }
    },
    "/v2/orders/{order_id}/confirmation": {
      "post": {
        "summary": "Confirm order",
        "description": "Confirms and returns Order. Orders with pending calculations cannot be confirmed.",
        "operationId": "confirmOrder",
        "security": [
          {
            "OAuth": ["orders"]
          }
        ],
        "tags": ["Orders v2"]
      }
    },
    "/v2/orders/{order_id}/order-items": {
      "get": {
        "summary": "Get Order Items",
        "description": "Returns Order items",
        "operationId": "getItemsByOrderId",
        "security": [
          {
            "OAuth": ["orders/read"]
          }
        ],
        "tags": ["Orders v2"]
      },
      "post": {
        "summary": "Create Order Item",
        "description": "Creates Item for Order",
        "operationId": "createItemByOrderId",
        "security": [
          {
            "OAuth": ["orders"]
          }
        ],
        "tags": ["Orders v2"]
      }
    },
    "/v2/orders/{order_id}/order-items/{order_item_id}": {
      "get": {
        "summary": "Get Order Item",
        "description": "Returns Order item",
        "operationId": "getItemById",
        "security": [
          {
            "OAuth": ["orders/read"]
          }
        ],
        "tags": ["Orders v2"]
      },
      "patch": {
        "summary": "Update Order Item",
        "description": "Make a partial update of an order item. NOTE that the source of the order item can't be changed via a PATCH request, to create an order item from another source you must delete the current one and add a new one.",
        "operationId": "updateItem",
        "tags": ["Orders v2"]
      },
      "delete": {
        "summary": "Delete Order Item",
        "description": "Remove a single item from the order",
        "operationId": "deleteItemById",
        "security": [
          {
            "OAuth": ["orders"]
          }
        ],
        "tags": ["Orders v2"]
      }
    },
    "/v2/orders/{order_id}/shipments": {
      "get": {
        "summary": "Get Shipments",
        "description": "Shipments contain information about how and when your orders items will be delivered and fulfilled",
        "operationId": "getShipments",
        "security": [
          {
            "OAuth": ["orders/read"]
          }
        ],
        "tags": ["Orders v2"]
      }
    },
    "/v2/sync-products": {
      "get": {
        "summary": "Get Sync Products",
        "description": "Get information about all Sync Products of your store.",
        "operationId": "getSyncProducts",
        "security": [
          {
            "OAuth": ["sync_products/read"]
          }
        ],
        "tags": ["Sync v2"]
      },
      "post": {
        "summary": "Create a Sync Product",
        "description": "Creates a new Sync Product.\n\n<div class=\"alert alert-danger\">\n  This endpoint is only available for \"Manual order platform / API\" stores (store type <code>native</code>). \n</div>\n",
        "operationId": "createSyncProduct",
        "security": [
          {
            "OAuth": ["sync_products/write"]
          }
        ],
        "tags": ["Sync v2"]
      }
    },
    "/v2/sync-products/{sync_product_id}": {
      "get": {
        "summary": "Get a Sync Product",
        "description": "Get information about a single Sync Product.",
        "operationId": "getSyncProductById",
        "security": [
          {
            "OAuth": ["sync_products/read"]
          }
        ],
        "tags": ["Sync v2"]
      },
      "delete": {
        "summary": "Delete a Sync Product",
        "description": "Deletes a single Sync Product.",
        "operationId": "deleteSyncProductById",
        "security": [
          {
            "OAuth": ["sync_products/write"]
          }
        ],
        "tags": ["Sync v2"]
      },
      "patch": {
        "summary": "Update a Sync Product",
        "description": "Make a partial update of a Sync Product. This endpoint allows you to replace all Sync Variants with new ones. If you want to update one or more Sync Variants, [Update a Sync Variant](#tag/Sync-v2/operation/updateSyncVariantInSyncProductById) endpoint should be used instead.",
        "operationId": "updateSyncSyncProductById",
        "security": [
          {
            "OAuth": ["sync_products/write"]
          }
        ],
        "tags": ["Sync v2"]
      }
    },
    "/v2/sync-variants/{sync_variant_id}": {
      "get": {
        "summary": "Get a Sync Variant",
        "description": "Get information about a single Sync Variant.",
        "operationId": "getSyncVariantById",
        "security": [
          {
            "OAuth": ["sync_products/read"]
          }
        ],
        "tags": ["Sync v2"]
      }
    },
    "/v2/sync-products/{sync_product_id}/sync-variants": {
      "get": {
        "summary": "Get Sync Variants",
        "description": "Get information about all the sync variants of a specific sync product.",
        "operationId": "getSyncProductVariants",
        "security": [
          {
            "OAuth": ["sync_products/read"]
          }
        ],
        "tags": ["Sync v2"]
      },
      "post": {
        "summary": "Create a Sync Variant",
        "description": "Creates a new Sync Variant for an existing Sync Product",
        "operationId": "createSyncVariant",
        "security": [
          {
            "OAuth": ["sync_products/write"]
          }
        ],
        "tags": ["Sync v2"]
      }
    },
    "/v2/sync-products/{sync_product_id}/sync-variants/{sync_variant_id}": {
      "delete": {
        "summary": "Delete a Sync Variant",
        "description": "Delete a single Sync Variant.",
        "operationId": "deleteSyncVariantInSyncProductById",
        "security": [
          {
            "OAuth": ["sync_products"]
          }
        ],
        "tags": ["Sync v2"]
      },
      "patch": {
        "summary": "Update a Sync Variant",
        "description": "Make a partial update of a Sync Variant. NOTE that the source of the Sync Variant can't be changed via a PATCH request, to create a Sync Variant from another source you must delete the current one and add a new one.",
        "operationId": "updateSyncVariantInSyncProductById",
        "security": [
          {
            "OAuth": ["sync_products/write"]
          }
        ],
        "tags": ["Sync v2"]
      }
    },
    "/v2/mockup-tasks": {
      "post": {
        "summary": "Create Mockup Generator tasks",
        "description": "Create Mockup Generator tasks",
        "operationId": "createMockupGeneratorTasks",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Mockup Generator v2"]
      },
      "get": {
        "summary": "Retrieve Mockup Generator tasks",
        "description": "Returns result of Mockup Generator tasks",
        "operationId": "getMockupGeneratorTasks",
        "security": [
          {
            "OAuth": []
          }
        ],
        "tags": ["Mockup Generator v2"]
      }
    },
    "/v2/webhooks": {
      "get": {
        "summary": "Get webhook configuration",
        "description": "Returns a configured webhook URL and a list of webhook event types enabled for the store",
        "operationId": "getWebhooks",
        "security": [
          {
            "OAuth": ["webhooks/read"]
          }
        ],
        "tags": ["Webhook v2"]
      },
      "post": {
        "summary": "Set up webhook configuration",
        "description": "Use this endpoint to enable a webhook URL for a store and select webhook event types that will be sent to this URL.\n\nNote that only one webhook configuration can be active for each private OAuth token or app, calling this method will disable the previous webhook configuration.\n\nSetting up the [Catalog stock updated](#operation/catalogStockUpdated) webhook requires passing products (currently only IDs are taken into account).\n\nStock update webhook will only include i[...]",
        "operationId": "createWebhook",
        "security": [
          {
            "OAuth": ["webhooks"]
          }
        ],
        "tags": ["Webhook v2"]
      },
      "delete": {
        "summary": "Disable webhook support",
        "description": "Removes the webhook URL and all event types from the store.",
        "operationId": "disableWebhook",
        "security": [
          {
            "OAuth": ["webhooks"]
          }
        ],
        "tags": ["Webhook v2"]
      }
    },
    "/v2/webhooks/{eventType}": {
      "get": {
        "summary": "Get event configuration",
        "description": "Returns event configuration for store",
        "operationId": "getWebhookEventConfiguration",
        "security": [
          {
            "OAuth": ["webhooks/read"]
          }
        ],
        "tags": ["Webhook v2"]
      },
      "post": {
        "summary": "Set up event configuration",
        "description": "Use this endpoint to create or replace specific event configuration for a store.\n\nSetting up the [Catalog stock updated](#operation/catalogStockUpdated) webhook requires passing products (currently only IDs are taken into account).\n\nStock update webhook will only include information for the products specified in the `products` param.\n",
        "operationId": "createWebhookEventConfiguration",
        "security": [
          {
            "OAuth": ["webhooks"]
          }
        ],
        "tags": ["Webhook v2"]
      },
      "delete": {
        "summary": "Disable support for event",
        "description": "Disables the event for a store and clears its configuration, leaving other webhooks intact.\n",
        "operationId": "disableWebhookEvent",
        "security": [
          {
            "OAuth": ["webhooks"]
          }
        ],
        "tags": ["Webhook v2"]
      }
    }
  },
  "x-webhooks": {
    "shipment_sent": {
      "post": {
        "summary": "Shipment sent",
        "operationId": "shipmentSent",
        "description": "Is called when a shipment with all or part of the ordered items is shipped.\n\n If the order is shipped in multiple shipments, this event will be called for every shipment sent.\n\n If some items are reshipped, a shipping notification will be sent again for the same items.",
        "tags": ["Webhook v2"]
      }
    },
    "shipment_returned": {
      "post": {
        "summary": "Shipment returned",
        "operationId": "shipmentReturned",
        "description": " Is called when a shipment is processed as returned to the fulfillment facility. To learn more about the reasons why a shipment might be returned, take a look at [Printful's Return Policy](https://www.printful.com/policies/returns) ",
        "tags": ["Webhook v2"]
      }
    },
    "order_created": {
      "post": {
        "summary": "Order created",
        "operationId": "orderCreated",
        "description": "Is called when the order is first created.",
        "tags": ["Webhook v2"]
      }
    },
    "order_updated": {
      "post": {
        "summary": "Order updated",
        "operationId": "orderUpdated",
        "description": "Is called when an existing order gets updated for any reason - including things that are covered with other webhooks like `order_canceled`.",
        "tags": ["Webhook v2"]
      }
    },
    "order_failed": {
      "post": {
        "summary": "Order failed",
        "operationId": "orderFailed",
        "description": "Is called when a confirmed order changes its status to `failed`.\n\n It can happen, for example, if printfiles can not be downloaded, are not valid image files or when there is a payment failure.",
        "tags": ["Webhook v2"]
      }
    },
    "order_canceled": {
      "post": {
        "summary": "Order canceled",
        "operationId": "orderCanceled",
        "description": "Is called when a confirmed order changes its status to `canceled`.\n\n It can happen when a submitted order is canceled from the dashboard or through the API or when the order is canceled by the Printful staff.",
        "tags": ["Webhook v2"]
      }
    },
    "product_synced": {
      "post": {
        "summary": "Product synced",
        "operationId": "productSynced",
        "description": "Is called when a new product or variant is imported from the store's ecommerce integration.\n\n See [Ecommerce Platform Sync API](#/tag/Ecommerce-Platform-Sync-API)",
        "tags": ["Webhook v2"]
      }
    },
    "product_updated": {
      "post": {
        "summary": "Product updated",
        "operationId": "productUpdated",
        "description": "Is called when a new product or variant is created or updated in any way.\n\n See [Ecommerce Platform Sync API](#/tag/Ecommerce-Platform-Sync-API)",
        "tags": ["Webhook v2"]
      }
    },
    "product_deleted": {
      "post": {
        "summary": "Product deleted",
        "operationId": "productDeleted",
        "description": "Is called when a new product or variant is deleted.\n\n See [Ecommerce Platform Sync API](#/tag/Ecommerce-Platform-Sync-API)",
        "tags": ["Webhook v2"]
      }
    },
    "catalog_stock_updated": {
      "post": {
        "summary": "Catalog stock updated",
        "operationId": "catalogStockUpdated",
        "description": "Is called when stock is updated for some of a product's variants.\n\n Contains information about the availability of product variants that have changed.",
        "tags": ["Webhook v2"]
      }
    },
    "catalog_price_changed": {
      "post": {
        "summary": "Catalog price changed",
        "operationId": "catalogPriceChanged",
        "description": "Is called when a catalog product price has changed.\n\n This webhook is related to the pricing endpoint.",
        "tags": ["Webhook v2"]
      }
    },
    "order_put_hold": {
      "post": {
        "summary": "Order put hold",
        "operationId": "orderPutHold",
        "description": "Is called when order is put on hold.",
        "tags": ["Webhook v2"]
      }
    },
    "order_put_hold_approval": {
      "post": {
        "summary": "Order put hold approval",
        "operationId": "orderPutHoldApproval",
        "description": "Is called when order is put on hold and there are changes that must be approved by the customer before fulfillment. Will contain a confirm hash that can be used to approve changes with the Approval Sheets Api.",
        "tags": ["Webhook v2"]
      }
    },
    "order_remove_hold": {
      "post": {
        "summary": "Order remove hold",
        "operationId": "orderRemoveHold",
        "description": "Is called when order is removed from hold.",
        "tags": ["Webhook v2"]
      }
    },
    "mockup_task_finished": {
      "post": {
        "summary": "Mockup task finished",
        "operationId": "mockupTaskFinished",
        "description": "Is called when a Mockup task is finished.\n\n This doesn't necessarily mean that the task has successfully finished\n\n it could also mean that the task has failed to generate.",
        "tags": ["Webhook v2"]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth": {
        "type": "oauth2",
        "description": "### Making authorized API calls\n\nTo make OAuth requests to the Printful API, `access_token` and `token_type` must be included in the request `Authorization` header.\n\n```\n# Authorized CURL request example with OAuth\ncurl -X GET 'https://api.printful.com/v2/sync-products' \\\n-H 'Authorization: Bearer smk_GN0I1Os3OdfqzjJnTOWn1wlbqqq2Y2Pc10TS'\n```",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://www.printful.com/oauth/token",
            "tokenUrl": "https://www.printful.com/oauth/token",
            "refreshUrl": "https://www.printful.com/oauth/token",
            "scopes": {
              "orders": "Read and Write access to Orders",
              "orders/read": "Read access to Orders",
              "stores_list": "Read and Write access to Stores",
              "stores_list/read": "Read access to Stores",
              "sync_products": "Read and Write access to SyncProducts",
              "sync_products/read": "Read access to SyncProducts",
              "file_library": "Read and Write access to File library",
              "file_library/read": "Read access to File library",
              "webhooks": "Read and Write access to Webhooks",
              "webhooks/read": "Read access to Webhooks"
            }
          }
        }
      }
    }
  }
}
